# Generated by Django 5.2.13 on 2026-09-28 15:27
#
# D-04: safety-net data migration backfilling "UTC" onto every pre-existing
# user row. This is a no-op in practice since AddField(default="UTC")
# already backfills every existing row at the schema level, but D-04
# explicitly asks for a data migration alongside the schema change — mirrors
# budget/migrations/0002_rename_redeemed_emergency_category.py's RunPython +
# apps.get_model shape.

from django.db import migrations, models


def backfill_utc(apps, schema_editor):
    CustomUser = apps.get_model("users", "CustomUser")
    CustomUser.objects.using(schema_editor.connection.alias).filter(
        timezone__isnull=True
    ).update(timezone="UTC")


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='timezone',
            field=models.CharField(default='UTC', max_length=64),
        ),
        migrations.RunPython(backfill_utc, migrations.RunPython.noop),
    ]
