# Generated by Django 5.2.13 on 2026-09-15 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_cards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='credit_cards.creditcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_card_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'credit card entry',
                'verbose_name_plural': 'credit card entries',
                'db_table': 'credit_card_entries',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['card', 'date'], name='idx_cc_entry_card_date')],
            },
        ),
    ]
