# Generated by Django 5.2.13 on 2026-09-15 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InitialBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_type', models.CharField(choices=[('bank', 'Bank'), ('emergency_fund', 'Emergency Fund')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('effective_month', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initial_balances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'initial balance',
                'verbose_name_plural': 'initial balances',
                'db_table': 'initial_balances',
                'constraints': [models.UniqueConstraint(fields=('user', 'balance_type'), name='unique_initial_balance_per_user_type')],
            },
        ),
    ]
