# Generated by Django 5.2.13 on 2026-09-28 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurring', '0001_initial'),
        ('transactions', '0002_initialbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='recurring_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_transactions', to='recurring.recurringentry'),
        ),
    ]
