# Generated by Django 5.2.13 on 2026-09-28 15:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budget', '0002_rename_redeemed_emergency_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(max_length=255)),
                ('day_of_month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_entries', to='budget.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'recurring entry',
                'verbose_name_plural': 'recurring entries',
                'db_table': 'recurring_entries',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RecurringGenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('recurring_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_log', to='recurring.recurringentry')),
            ],
            options={
                'verbose_name': 'recurring generation log',
                'verbose_name_plural': 'recurring generation logs',
                'db_table': 'recurring_generation_log',
                'constraints': [models.UniqueConstraint(fields=('recurring_entry', 'period'), name='unique_generation_per_entry_period')],
            },
        ),
    ]
